### ISSUE TITLE
No @Param annotation found on query method findByAddressLocationNear

### ISSUE THREAD

**Issue by harshavmb** [spring-projects/spring-data-examples#277]
Having imported and run starbucks rest project, the _findByAddressLocationNear_ method in _StoreRepository_ interface is throwing the below error with the below stack trace.

> java.lang.IllegalArgumentException: No @Param annotation found on query method findByAddressLocationNear

I know this was already raised before [https://jira.spring.io/browse/DATAREST-187](url) and I could see not yet resolved.

To suppress the error, have modified the below statement from 

```
@RestResource(rel = "by-location")
	Page<Store> findByAddressLocationNear(Point location, Distance distance, Pageable pageable);
```  
to 

```
@RestResource(rel = "by-location")
	Page<Store> findByAddressLocationNear(@Param("location") Point location, @Param("distance") Distance distance,
			@Param("pageable") Pageable pageable);
```
As a workaround, any chance this code be merged to suppress the error?

**Comment by schauder** [comment]
Do you see this during test execution or when actually running the code? Did you build it using Maven? Because the pom.xml of the root project specifies compilation with `-parameter` which should take care of this issue.

**Comment by harshavmb** [comment]
I saw the error when running the actual code. Just ran it with 

> mvn spring-boot:run 
command. Actually, I didn't clone the project. Have created my own spring-project and copied the code. I didn't get 

> Because the pom.xml of the root project specifies compilation with -parameter which should take care of this issue.

Could you please elaborate? Sorry, am not that good at spring and maven, question might sound silly!

**Comment by schauder** [comment]
> Sorry, am not that good at spring and maven, question might sound silly!

No problem, I'm the new guy in the team and really good at asking silly questions.

Spring Data tries to get the information you provide with `@Param` from the actual Bytecode. This works because from Java 8 on the java compiler does actually store the parameter names in the byte code, but only when `javac` is called with the `-parameter` flag.

So what you have to do is configure Maven to do so, i.e. you add a configuration for the maven-compiler-plugin. [This is already done in the examples project](https://github.com/spring-projects/spring-data-examples/blob/master/pom.xml#L110), and you probably can copy it almost verbatim from there into your `pom.xml`

**Comment by harshavmb** [comment]
Aww..!! Thanks. Saw the 

> compilerArgument

tag.
