### ISSUE TITLE
Upgrade to Spring Boot 1.5.4

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-data-examples#279]

**Comment by arashkhalesi** [comment]
Hi Oliver,I am trying to SELECT specific column by  JPA specification , The column has @ManyToOne  to the owner (Master)
Master --> 1:N   detail Detail   M:N   Master 

I cannot use Named Query since I have a lot of condition to check so the CriteriaBuilder is the only option I have basically I query.multiselect with 1 element only but  this is not working at all 
Parameter value [org.springframework.data.jpa.domain.Specifications@4ac10478] did not match expected type [java.lang.String (n/a)]


i am sure there is a issue with naming "findMasterByEventByIdAndByName()" 
I would appreciate to let me know if there is any solution for this. 
I am using Spring-boot, 1.5.2.RELEASE
@Entity@Table(name = "master")public class Master {    @Id    @Column(name = "master_id")    private Integer id;     @OneToMany(mappedBy = "masters", fetch = FetchType.EAGER)
    private List<Detail> details= new HashMap<>();}------------------------------------------------@Entity@Table(name = "detail")public class Detail {    @Id    @Column(name = "detail_id")    private Integer id   @ManyToOne(name="event_id")    @JoinColumn(name = "name")    private Event event;
    @ManyToOne    @JoinColumn(name = "master_id")    private Master master;}--------------------------------------------------public interface DetailsRespository extends JpaRepository<Detail, Serializable>, JpaSpecificationExecutor<Details> { Page<Master>  findMasterByEventByIdAndByName(Specification<> specs,Pageable pageable);}
 public Predicate toPredicate(Root<Detail> root, CriteriaQuery<?> query, CriteriaBuilder cb) {
        if (criteria.getOperation().equalsIgnoreCase("join")) {            Join<Detail, Master> master = root.join("master", JoinType.INNER);                      List<Selection<? extends Master>> selectionList = new ArrayList<Selection<? extends Object>>();             Selection<? extends Master> selection = root.get("master");            selectionList.add(selection);            query.multiselect(selectionList);
            query.distinct(true);
 Thanks 
Ara

**Comment by olivergierke** [comment]
This is a bug tracker, for general question please use stackoverflow.com.
