### ISSUE TITLE
Spring Data JDBC - Demonstrate jOOQ integration

### ISSUE THREAD

**Issue by schauder** [spring-projects/spring-data-examples#315]

**Comment by awaisraad** [comment]
There is already an example in Spring Boot examples section.

Check it out:
https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-jooq

**Comment by schauder** [comment]
Thanks for the pointer, but that is not for integration with Spring Data JDBC.

**Comment by florianluediger** [comment]
@schauder what exactly do you want to show with this issue? Do you want to show how to somehow add custom queries to the project itself with jOOQ, like in [this example for MyBatis](https://github.com/spring-projects/spring-data-examples/blob/master/jdbc/mybatis/src/main/resources/example/springdata/jdbc/mybatis/Model.xml#L6). Or do you want to show how to use a Spring Data JDBC application together with jOOQ, like in [this example with r2bc](https://github.com/spring-projects/spring-data-examples/blob/master/jdbc/r2dbc/src/test/java/example/springdata/r2dbc/basics/CustomerRepositoryIntegrationTests.java#L52)?

**Comment by schauder** [comment]
I've imagined just a simple custom method implementation for a repository that uses jOOQ.

**Comment by florianluediger** [comment]
@schauder I think I am still not really understanding what exactly you want. As I understand it, you want to create a custom method like with the _Query_-annotation, demonstrated [here](https://github.com/spring-projects/spring-data-examples/blob/master/jdbc/r2dbc/src/main/java/example/springdata/r2dbc/basics/CustomerRepository.java#L28), for example.

Just instead of the provided _Query_-annotation, you want to use jOOQ, correct? This is not directly possible as far as I can see, because the Repository has to be an interface to be autowired (?) and therefore does not allow method implementations which could use jOOQ. I might of course be able to create a new class containing some custom methods, however that would not really be an "integration" with Spring Data JDBC in my opinion. Maybe I am getting something completely wrong.

I could not find many examples for creating _any_ custom method implementation, except from the examples using the _Query_-annotation and the MyBatis examples, both of which were not a great starting point to work on this issue for me. Maybe you can give me a hint where it would make sense to start with this.

**Comment by schauder** [comment]
Your confusion is understandable.

>  I might, of course, be able to create a new class containing some custom methods, however, that would not really be an "integration" with Spring Data JDBC in my opinion.

While I agree that really isn't that much of an integration it's exactly what I want for this example.
The point is that after talking with Lukas Eder (creator of jOOQ) about this there really doesn't seem to be any need for a tighter integration.

Of course, if you or anybody else comes up with an idea for a tighter integration I'm open to feature requests.

**Comment by florianluediger** [comment]
I am currently working on this issue, however I can not get the jOOQ maven plugin to generate me any sources. Can you take a look at my [Stackoverflow question](https://stackoverflow.com/questions/51328307/jooq-does-not-generate-sources) and maybe help me figure this out?

**Comment by schauder** [comment]
I'd have to dig into that and currently don't have the time. So if you need help with it fast you could ping the god creator of jOOQ Lukas Eder on twitter. Chances are good he spots the problem right away.

**Comment by schauder** [comment]
I think the problem is that you are specifying an in-memory database URL as the source for code generation. This will start the in-memory database, but it won't have any schema objects inside, so nothing gets generated. 

I'd expect the DDL generator to fix this: https://www.jooq.org/doc/3.11/manual/code-generation/codegen-ddl/

**Comment by florianluediger** [comment]
That actually fixed my problem, thanks for the info! I have created a PR now, so feel free to have a look: #385

**Comment by schauder** [comment]
Done. Thanks @florianluediger
