### ISSUE TITLE
Spring Data Reactive - Demonstrate possibility of standalone usage (not Spring container)

### ISSUE THREAD

**Issue by soberich** [spring-projects/spring-data-examples#334]
Hi, 
I see there is a super short description on standalone usage of spring-data-jpa
(which is not as sufficient as it could be even for a bare minimum)
This is a wonderful set of features (classes) which would be very helpful in any project. I wonder if
0. Standalone = does this mean spting-data-jpa could be used in CDI contianer, maybe even OSGi container (the second at least in principle) ?
1. The description could be more than (https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.create-instances.standalone)
2. The example could be provided as the only existent is 5 years old now https://github.com/geowarin/hibernate-examples/tree/master/standalone-data-jpa
3. And the core of this request is - "Is it possible to use a standalone reactive data jpa?" 
& also if, say we only aim to return CompletableFuture like in example 
`CompletableFuture<User> findOneByFirstname(String firstname);`
but with no @Async annotation as this is container specific.
Thanks, Serge

**Comment by olivergierke** [comment]
For general questions please use StackOverflow. In short:

1. The CDI extension is documented in the [reference documentation](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpd.misc.cdi-integration) (CMD+F, "CDI"). 
3. There's not reactive implementation for JPA because it's a blocking API. `CompletableFuture` is not reactive API either. And yes, the asynchronous invocation is container specific. It can't be part of our CDI integration as `@Asynchronous` lives in EJB, not CDI.
