### ISSUE TITLE
An issue in spring-data-examples/rest/multi-store/ example

### ISSUE THREAD

**Issue by afattahi54** [spring-projects/spring-data-examples#403]
At `spring-data-examples/rest/multi-store/` 

I find this line on read me:

> Notice how @EnableJpaRepositories(basePackageClasses = Person.class) uses Person as a tip off of what package to start scanning for JPA entities

But could not find `@EnableJpaRepositories(basePackageClasses = Person.class)`  in any classes.

Is it ok?!

**Comment by ThomasVitale** [comment]
The `@EnableJpaRepositories` annotation is not needed in the multi-store example. Maybe the description in the readme file might be rephrased to better explain that it's an option that can be used if you need to get more control, but it's actually not necessary in the example.

In the actual multi-store app, using the `@SpringBootApplication` annotation, it's not needed because of what explained in the [Spring Data JPA getting started guide](https://spring.io/guides/gs/accessing-data-jpa/):

> By default, Spring Boot will enable JPA repository support and look in the package (and its subpackages) where @SpringBootApplication is located. If your configuration has JPA repository interface definitions located in a package not visible, you can point out alternate packages using @EnableJpaRepositories and its type-safe basePackageClasses=MyRepository.class parameter. 

In the class example shown in the readme file, containing the `@EnableAutoConfiguration` annotation, it's not needed because of what explained in the [Spring Boot docs](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-data-access.html#howto-use-spring-data-repositories):

> Spring Boot tries to guess the location of your @Repository definitions, based on the @EnableAutoConfiguration it finds. To get more control, use the @EnableJpaRepositories annotation (from Spring Data JPA).
