### ISSUE TITLE
Spring Data Jpa Optional Feature

### ISSUE THREAD

**Issue by cristianprofile** [spring-projects/spring-data-examples#49]
When i try to use this method Optional<Customer> findOne(Long id); at a repository class, compiler error is thrown, is it allowed to use this feature at last Spring Data Jpa release on maven central?

https://github.com/spring-projects/spring-data-examples/tree/master/jpa/java8

A lot of thanks for you support !!!!!

**Comment by olivergierke** [comment]
Yes, the `Optional` support has been in released versions for quite a while already. The thing you have to consider is that you cannot extend `CrudRepository` if you want to declare methods like `findOne(…)` with a return type of `Optional`. This is due to the fact that `CrudRepository` already declares a `findOne(…)` returning `T` and thus the compiler will complain about incompatible return types.

**Comment by cristianprofile** [comment]
Is it planned to integrate the feature with optional return value at findone operation on
JpaRepository<Object, Long>? A lot of thanks for your support.

**Comment by olivergierke** [comment]
No, as this would be an incompatible and Java 8 enforcing change to the API. Work around this limitation by creating a dedicated base repository interface yourself just as it's shown in the example I linked to.

Generally speaking, this is the tracker for the examples. For general purpose questions, please [post on StackOverflow](http://stackoverflow.com/questions/tagged/spring-data). For bug reports and feature requests please use the [individual project](https://jira.spring.io/secure/BrowseProjects.jspa#10000)'s tracker in our JIRA instance.

**Comment by cristianprofile** [comment]
Thank your for your support and for Spring Data Module, sorry for place this question to wrong place.
