### ISSUE TITLE
Create JPA example based on EclipseLink

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-data-examples#50]
Based on [this request](https://jira.spring.io/browse/DATAJPA-626).

- Spring Boot with Eclipselink instead of Hibernate
- Project configured to use static weaving

**Comment by jrrickard** [comment]
Is anyone working on this? I'm willing to make an example.

**Comment by ThomBrando** [comment]
Please keep in mind that it would be most helpful if the example used a database that wasn't in memory, or at least explained what changes would be needed to use it as a model for apps that don't use in-memory databases.  For those of us still on the steep part of the learning curve.  8^)

**Comment by olivergierke** [comment]
I'd argue that's an orthogonal problem. You basically swap out the `DataSource` the app should be using. In Boot this is achieved by just declaring an `@Bean`-method returning a `DataSource`.

**Comment by ThomBrando** [comment]
I started with an Application class that was identical to the one in the example.  There was no DataSource definition I could find, so I added the following to the Application class:

    @Bean
    public DataSource dataSource() {
        JndiObjectFactoryBean jndiObjectFactoryBean = new JndiObjectFactoryBean();
        jndiObjectFactoryBean.setJndiName("java:comp/env/jdbc/EEVDataSource");
        try {
            jndiObjectFactoryBean.afterPropertiesSet();
        } catch (NamingException e) {
            System.err.println("Error retrieving datasource: " + e);
        }
        return (DataSource) jndiObjectFactoryBean.getObject();
    }

I didn't get the nifty Spring Data ascii art when the app started up until I changed the Application class to extend SpringBootServletInitializer instead of JpaBaseConfiguration.  Then I'd get the nifty ascii art, but also the error message:

"NoSuchBeanDefinitionException: No bean named 'entityManagerFactory' is defined"

and that started me on the path to adding more and more bean definitions to my Application class until I gave up and submitted my comment to the thread https://github.com/spring-projects/spring-boot/issues/1268#ref-commit-59ce634

That's why I mentioned it here.

**Comment by olivergierke** [comment]
Please let's not side track this ticket here. This is about configuring Spring Data JPA to run on EclipseLink, not DataSource customizations within Boot. I guess the ticket in Boot is the more correct place to discuss this, so feel free to submit a sample project that shows the error in a test case or the like.
