### ISSUE TITLE
https://stackoverflow.com/questions/61056287/java-lang-illegalargumentexception-expected-unique-result-or-null-but-got-more

### ISSUE THREAD

**Issue by javaHelper** [spring-projects/spring-data-examples#559]
Could you please guide me here : https://stackoverflow.com/questions/61056287/java-lang-illegalargumentexception-expected-unique-result-or-null-but-got-more ?

**Comment by schauder** [comment]
This is the issue tracker for spring data examples. Create issues here if you find a bug in the examples or have an idea for an improvement  of the examples. 

For support question SO is the right address. 

Issues like this just take away time from the team because someone has to write messages like this one, thereby reducing the chances of receiving help with your question.
