### ISSUE TITLE
Add example for Java 8 Streams via default method.

### ISSUE THREAD

**Issue by thomasdarimont** [spring-projects/spring-data-examples#60]
We should show how to use Java 8 Streams in a default method by delegating to another finder and calling stream() on the result.

**Comment by olivergierke** [comment]
Is that example really something we'd recommend people to do? Turning a `List` into a `Stream` i a default method replaces a single method call on the `List` with an additional method declaration on the repository. Also, it doesn't really create any of the benefits you'd usually get when declaring a `Stream` method on the repository (actually streaming the results).

**Comment by thomasdarimont** [comment]
I just wanted to highlight two different ways to use Java 8 Streams - the variant with the default method simply shows how easy it is to extend the existing API without having to call stream() on the result yourself - this makes for shorter examples and demonstrates another use of default methods.

**Comment by olivergierke** [comment]
To me it looks more like a "because you can" rather than something really useful. Would you really add three more lines and an additional repository method instead of just calling `….stream()` on the client? Especially if it doesn't really give you a `Stream` but only a streaming view of the list? Why not declare an additional, really streaming method? You write less code and actually get the benefits of the new return type. IYAM, what we have in #62 is short, concise and practical.

**Comment by mp911de** [comment]
Since we have native `Stream` support, this issue is no longer valid.
