### ISSUE TITLE
Connect to Huawei Cloud guassDB

### ISSUE THREAD

**Issue by 415212048** [spring-projects/spring-data-examples#674]
It is hoped that the guassdb connected to Huawei Cloud can be extended

**Comment by schauder** [comment]
For Spring Relational we currently do not plan to support more databases, but you can always implement your own `Dialect` which should be sufficient for Spring Data JDBC. For Spring Data R2DBC you'd need a suitable driver first.

For Spring Data JPA you'd have to talk to the team creating your preferred JPA implementation (e.g. Hibernate). They also offer a `Dialect` abstraction that should allow you to support additional databases.

And since this is the examples project: we also won't create examples for each and every database.
